# Generated by Django 5.2 on 2025-05-06 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("departments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Guard",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="guards", to="departments.department"
                    ),
                ),
            ],
            options={
                "verbose_name": "Гуард",
                "verbose_name_plural": "Гуарды",
            },
        ),
        migrations.CreateModel(
            name="GuardOperation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("CREATE", "Создание"),
                            ("READ", "Чтение"),
                            ("UPDATE", "Обновление"),
                            ("DELETE", "Удаление"),
                        ],
                        max_length=255,
                        verbose_name="Операция",
                    ),
                ),
                (
                    "guard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="operations", to="guards.guard"
                    ),
                ),
            ],
            options={
                "verbose_name": "Операция гуарда",
                "verbose_name_plural": "Операции гуарда",
            },
        ),
        migrations.AddIndex(
            model_name="guard",
            index=models.Index(fields=["title"], name="guards_guar_title_3d3122_idx"),
        ),
        migrations.AddIndex(
            model_name="guard",
            index=models.Index(fields=["department"], name="guards_guar_departm_7e3c2a_idx"),
        ),
        migrations.AddIndex(
            model_name="guardoperation",
            index=models.Index(fields=["guard"], name="guards_guar_guard_i_3c23d7_idx"),
        ),
        migrations.AddIndex(
            model_name="guardoperation",
            index=models.Index(fields=["operation"], name="guards_guar_operati_9888af_idx"),
        ),
    ]
