# Generated by Django 5.2 on 2025-05-06 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("departments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                ("code", models.CharField(max_length=64, verbose_name="Код")),
                ("tag", models.CharField(max_length=64, verbose_name="Тег")),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Активный"), ("FINISHED", "Завершен")],
                        default="ACTIVE",
                        max_length=64,
                        verbose_name="Статус",
                    ),
                ),
                ("start_date", models.DateTimeField(verbose_name="Дата начала")),
                ("end_date", models.DateTimeField(verbose_name="Дата окончания")),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="departments.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Проект",
                "verbose_name_plural": "Проекты",
                "indexes": [
                    models.Index(fields=["title"], name="projects_pr_title_ba614c_idx"),
                    models.Index(fields=["status"], name="projects_pr_status_f023cb_idx"),
                    models.Index(fields=["department"], name="projects_pr_departm_4077ca_idx"),
                ],
            },
        ),
    ]
