# Generated by Django 5.2 on 2025-05-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="end_date",
            field=models.DateField(verbose_name="Дата окончания"),
        ),
        migrations.AlterField(
            model_name="project",
            name="start_date",
            field=models.DateField(verbose_name="Дата начала"),
        ),
    ]
