# Generated by Django 5.2 on 2025-05-06 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Journal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Создан"),
                            ("UPDATE", "Обновлен"),
                            ("DELETE", "Удален"),
                            ("RESTORE", "Восстановлен"),
                            ("APPROVE", "Одобрен"),
                        ],
                        max_length=64,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="journals", to="documents.document"
                    ),
                ),
            ],
            options={
                "verbose_name": "Журнал",
                "verbose_name_plural": "Журналы",
            },
        ),
    ]
