# Generated by Django 5.2 on 2025-05-06 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("journal", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="journal",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="journals", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddIndex(
            model_name="journal",
            index=models.Index(fields=["action"], name="journal_jou_action_0f1469_idx"),
        ),
        migrations.AddIndex(
            model_name="journal",
            index=models.Index(fields=["document"], name="journal_jou_documen_097dd8_idx"),
        ),
        migrations.AddIndex(
            model_name="journal",
            index=models.Index(fields=["user"], name="journal_jou_user_id_b6de23_idx"),
        ),
    ]
