# Generated by Django 5.2 on 2025-05-07 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="journal",
            name="details",
            field=models.TextField(blank=True, null=True, verbose_name="Детали"),
        ),
    ]
