# Generated by Django 5.2 on 2025-05-06 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                ("file_path", models.FileField(upload_to="documents/", verbose_name="Файл")),
                ("doc_number", models.CharField(max_length=255, verbose_name="Номер документа")),
                ("doc_type", models.CharField(max_length=255, verbose_name="Тип документа")),
                ("version_number", models.PositiveIntegerField(verbose_name="Версия документа")),
                ("size", models.CharField(max_length=255, verbose_name="Размер файла")),
                (
                    "status",
                    models.CharField(
                        choices=[("DRAFT", "Черновик"), ("HARMONIZATION", "На утверждение"), ("APPROVED", "Одобрено")],
                        default="DRAFT",
                        max_length=64,
                        verbose_name="Cтатус",
                    ),
                ),
            ],
            options={
                "verbose_name": "Документ",
                "verbose_name_plural": "Документы",
            },
        ),
        migrations.CreateModel(
            name="DocumentPermission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Права на документ",
                "verbose_name_plural": "Права на документы",
            },
        ),
        migrations.CreateModel(
            name="DocumentVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version_number", models.PositiveIntegerField(verbose_name="Версия документа")),
                ("file_path", models.FileField(upload_to="documents/", verbose_name="Файл")),
            ],
            options={
                "verbose_name": "Версия документа",
                "verbose_name_plural": "Версии документов",
            },
        ),
    ]
