# Generated by Django 5.2 on 2025-05-06 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("documents", "0001_initial"),
        ("guards", "0001_initial"),
        ("projects", "0001_initial"),
        ("tags", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="documents", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="documents", to="projects.project"
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="tag",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="documents", to="tags.tag"
            ),
        ),
        migrations.AddField(
            model_name="documentpermission",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="permissions", to="documents.document"
            ),
        ),
        migrations.AddField(
            model_name="documentpermission",
            name="guard",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="document_permissions", to="guards.guard"
            ),
        ),
        migrations.AddField(
            model_name="documentpermission",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="document_permissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="documentversion",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="versions", to="documents.document"
            ),
        ),
        migrations.AddField(
            model_name="documentversion",
            name="modified_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="document_versions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["title"], name="documents_d_title_ccf306_idx"),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["size"], name="documents_d_size_4e1cb7_idx"),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["status"], name="documents_d_status_07369e_idx"),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["project"], name="documents_d_project_43ce81_idx"),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["tag"], name="documents_d_tag_id_c16fb5_idx"),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["created_at"], name="documents_d_created_3b0a51_idx"),
        ),
        migrations.AddIndex(
            model_name="documentpermission",
            index=models.Index(fields=["user"], name="documents_d_user_id_61e778_idx"),
        ),
        migrations.AddIndex(
            model_name="documentpermission",
            index=models.Index(fields=["document"], name="documents_d_documen_bdbce8_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="documentpermission",
            unique_together={("user", "document")},
        ),
        migrations.AddIndex(
            model_name="documentversion",
            index=models.Index(fields=["version_number"], name="documents_d_version_3790b2_idx"),
        ),
    ]
