# Generated by Django 5.2 on 2025-05-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="document",
            old_name="file_path",
            new_name="file",
        ),
        migrations.RenameField(
            model_name="documentversion",
            old_name="file_path",
            new_name="file",
        ),
        migrations.AlterField(
            model_name="document",
            name="version_number",
            field=models.PositiveIntegerField(default=1, verbose_name="Версия документа"),
        ),
    ]
