# Generated by Django 5.2 on 2025-05-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_rename_file_path_document_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="content_type",
            field=models.CharField(max_length=255, null=True, verbose_name="Тип контента"),
        ),
    ]
