# Generated by Django 5.2 on 2025-05-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0004_document_content_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentversion",
            name="content_type",
            field=models.CharField(max_length=255, null=True, verbose_name="Тип контента"),
        ),
        migrations.AddField(
            model_name="documentversion",
            name="doc_title",
            field=models.CharField(max_length=255, null=True, verbose_name="Заголовок документа"),
        ),
        migrations.AddField(
            model_name="documentversion",
            name="doc_type",
            field=models.CharField(max_length=255, null=True, verbose_name="Тип документа"),
        ),
        migrations.AddField(
            model_name="documentversion",
            name="size",
            field=models.CharField(max_length=255, null=True, verbose_name="Размер файла"),
        ),
    ]
