# Generated by Django 5.2 on 2025-05-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0005_documentversion_content_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Черновик"),
                    ("ARCHIVE", "В архиве"),
                    ("HARMONIZATION", "На утверждение"),
                    ("APPROVED", "Одобрено"),
                ],
                default="DRAFT",
                max_length=64,
                verbose_name="Cтатус",
            ),
        ),
    ]
