# Generated by Django 5.2 on 2025-05-06 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("departments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                ("color", models.CharField(default="#d8ff75", max_length=64, verbose_name="Цвет")),
                ("summary", models.TextField(blank=True, null=True, verbose_name="Описание")),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="tags", to="departments.department"
                    ),
                ),
            ],
            options={
                "verbose_name": "Тег",
                "verbose_name_plural": "Теги",
                "indexes": [
                    models.Index(fields=["title"], name="tags_tag_title_fb756e_idx"),
                    models.Index(fields=["department"], name="tags_tag_departm_f1c8db_idx"),
                ],
            },
        ),
    ]
