INSTALLED_APPS = [
    "corsheaders",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.postgres",
    "django_redis",
    "rest_framework",
    "django_filters",
    "django_cleanup",
    "tags.infrastructure.apps.TagsConfig",
    "users.infrastructure.apps.UsersConfig",
    "departments.infrastructure.apps.DepartmentsConfig",
    "drf_spectacular",
]
