# Generated by Django 5.2 on 2025-05-12 17:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("departments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DepartmentSubscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start_date", models.DateField(verbose_name="Дата начала")),
                ("end_date", models.DateField(verbose_name="Дата окончания")),
                ("is_active", models.BooleanField(default=True, verbose_name="Активно")),
                ("auto_pay", models.BooleanField(default=False, verbose_name="Автоплатеж")),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="departments.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подписка",
                "verbose_name_plural": "Подписки",
            },
        ),
        migrations.CreateModel(
            name="DepartmentWallet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(0, message="Сумма не может быть отрицательной")
                        ],
                        verbose_name="Остаток средств",
                    ),
                ),
                (
                    "department",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="wallet", to="departments.department"
                    ),
                ),
            ],
            options={
                "verbose_name": "Баланс отдела",
                "verbose_name_plural": "Балансы отделов",
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payment_id",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="ID платежа YooKassa"),
                ),
                ("payment_url", models.URLField(blank=True, null=True, verbose_name="Ссылка на оплату")),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("bank_card", "Банковская карта"),
                            ("sberbank", "SberPay"),
                            ("tinkoff_bank", "T‑Pay"),
                            ("sbp", "СБП (Система быстрых платежей)"),
                            ("yoo_money", "ЮMoney"),
                            ("balance", "С лицевого счета"),
                            ("cashless", "Безналичная оплата"),
                        ],
                        max_length=32,
                        null=True,
                        verbose_name="Способ оплаты",
                    ),
                ),
                (
                    "payer_type",
                    models.CharField(
                        choices=[("INDIVIDUAL", "Физическое лицо"), ("LEGAL", "ЮЛ / ИП")],
                        max_length=32,
                        verbose_name="Тип плательщика",
                    ),
                ),
                (
                    "target",
                    models.CharField(
                        choices=[("WALLET", "Пополнение баланса"), ("PAYMENT", "Платеж")],
                        max_length=32,
                        verbose_name="Цель оплаты",
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="Назначение платежа"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name="Сумма оплаты"
                    ),
                ),
                ("is_paid", models.BooleanField(default=False, verbose_name="Оплачен")),
                (
                    "expires_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Дата истечения срока действия"),
                ),
                ("captured_at", models.DateTimeField(blank=True, null=True, verbose_name="Дата оплаты счета")),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="departments.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Счет",
                "verbose_name_plural": "Счета",
            },
        ),
    ]
